# Generated by Django 3.1.2 on 2020-10-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_eventgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgallery',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
