# Generated by Django 3.1.2 on 2020-10-31 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0003_auto_20201031_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgallery',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
