# Generated by Django 3.1.2 on 2020-11-01 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_auto_20201031_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='eventpics')),
                ('place', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
