# Generated by Django 3.1.2 on 2020-11-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0009_auto_20201101_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeevent',
            name='file',
            field=models.FileField(default='/media/eventfiles/def.pdf', upload_to='eventfiles'),
        ),
    ]
